# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbregistrering
team: teamregistrering
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbregistrering/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbregistrering/internal/selftest
    initialDelay: 60
prometheus:
  enabled: true
  path: veilarbregistrering/internal/metrics
resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  limits:
    cpu: 3
    memory: 1024Mi
  requests:
    memory: 512Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarbregistrering
    resourceType: loadbalancerconfig
  - alias: veilarbregistreringDB
    resourceType: datasource
  - alias: srvveilarbregistrering
    resourceType: credential
  - alias: veilarbregistrering.properties
    resourceType: applicationproperties
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: feature_endpoint
    resourceType: restservice
  - alias: virksomhet:Arbeidsforhold_v3
    resourceType: webserviceendpoint
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: veilArbOppfolgingAPI
    resourceType: restservice
  - alias: abac.pdp.endpoint
    resourceType: restservice

  # oidc med AzureAD B2C
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice
    propertyMap:
            url: OIDC_REDIRECT_URL
  exposed:
  - alias: veilarbregistreringSBS
    resourceType: restservice
    path: /veilarbregistrering/api
alertProfiles:
  - common-java-modules
